中	NR	b	1	-NONE-	in
国	NR	i	10	ROOT	out
最	JJ	b	3	-NONE-	in
大	JJ	i	10	ROOT	out
氨	NN	b	5	-NONE-	in
纶	NN	i	6	-NONE-	in
丝	NN	i	10	ROOT	out
生	NN	b	10	ROOT	out
产	NN	i	7	-NONE-	in
基	NN	b	10	-NONE-	in
地	NN	i	15	ROOT	out
在	P	b	15	ROOT	out
连	NR	b	13	-NONE-	in
云	NR	i	14	-NONE-	in
港	NR	i	11	ROOT	out
建	VV	b	-1	ROOT	out
成	VV	i	15	-NONE-	in

新	NN	b	1	-NONE-	in
华	NN	i	2	-NONE-	in
社	NN	i	4	ROOT	out
南	NR	b	4	-NONE-	in
京	NR	i	-1	ROOT	out
十	NT	b	6	-NONE-	in
二	NT	i	7	-NONE-	in
月	NT	i	4	ROOT	out
四	NT	b	9	-NONE-	in
日	NT	i	4	ROOT	out
电	NN	b	4	ROOT	out

中	NR	b	1	-NONE-	in
国	NR	i	3	ROOT	out
最	AD	b	3	ROOT	out
大	VA	b	4	ROOT	out
的	DEC	b	11	ROOT	out
氨	NN	b	6	-NONE-	in
伦	NN	i	7	-NONE-	in
丝	NN	i	11	ROOT	out
生	NN	b	11	ROOT	out
产	NN	i	8	-NONE-	in
基	NN	b	11	-NONE-	in
地	NN	i	32	ROOT	out
－	PU	b	11	ROOT	out
－	PU	i	12	-NONE-	in
钟	NR	b	15	-NONE-	in
山	NR	i	21	ROOT	out
氨	NN	b	17	-NONE-	in
伦	NN	i	21	ROOT	out
有	JJ	b	21	ROOT	out
限	JJ	i	18	-NONE-	in
公	NN	b	21	-NONE-	in
司	NN	i	12	ROOT	out
，	PU	b	32	ROOT	out
日	NT	b	24	-NONE-	in
前	NT	i	32	ROOT	out
在	P	b	32	ROOT	out
连	NR	b	27	-NONE-	in
云	NR	i	28	-NONE-	in
港	NR	i	31	ROOT	out
开	NN	b	31	-NONE-	in
发	NN	i	29	-NONE-	in
区	NN	i	25	ROOT	out
建	VV	b	-1	ROOT	out
成	VV	i	32	-NONE-	in
并	CC	b	32	ROOT	out
投	VV	b	32	ROOT	out
产	VV	i	35	-NONE-	in
。	PU	b	32	ROOT	out

这	DT	b	1	ROOT	out
个	M	b	18	ROOT	out
采	VV	b	16	ROOT	out
用	VV	i	2	-NONE-	in
差	NN	b	5	-NONE-	in
别	NN	i	6	-NONE-	in
化	NN	i	13	ROOT	out
氨	NN	b	8	-NONE-	in
伦	NN	i	9	-NONE-	in
丝	NN	i	13	ROOT	out
生	NN	b	13	ROOT	out
产	NN	i	10	-NONE-	in
技	NN	b	13	-NONE-	in
术	NN	i	2	ROOT	out
改	VV	b	2	ROOT	out
造	VV	i	14	-NONE-	in
的	DEC	b	18	ROOT	out
项	NN	b	18	-NONE-	in
目	NN	i	26	ROOT	out
，	PU	b	26	ROOT	out
总	JJ	b	21	ROOT	out
投	NN	b	26	ROOT	out
资	NN	i	21	-NONE-	in
七	CD	b	24	-NONE-	in
千	CD	i	25	-NONE-	in
万	CD	i	26	ROOT	out
元	M	b	31	ROOT	out
，	PU	b	31	ROOT	out
累	AD	b	29	-NONE-	in
计	AD	i	31	ROOT	out
年	AD	b	31	ROOT	out
产	VV	b	-1	ROOT	out
氨	NN	b	33	-NONE-	in
纶	NN	i	34	-NONE-	in
丝	NN	i	31	ROOT	out
一	CD	b	36	-NONE-	in
千	CD	i	37	-NONE-	in
五	CD	i	38	-NONE-	in
百	CD	i	39	ROOT	out
吨	M	b	31	ROOT	out
。	PU	b	31	ROOT	out

连	NR	b	1	-NONE-	in
云	NR	i	2	-NONE-	in
港	NR	i	11	ROOT	out
钟	NR	b	4	-NONE-	in
山	NR	i	11	ROOT	out
氨	NN	b	6	-NONE-	in
纶	NN	i	7	-NONE-	in
丝	NN	i	11	ROOT	out
有	JJ	b	11	ROOT	out
限	JJ	i	8	-NONE-	in
公	NN	b	11	-NONE-	in
司	NN	i	12	ROOT	out
是	VC	b	-1	ROOT	out
九	NT	b	14	-NONE-	in
十	NT	i	16	-NONE-	in
年	NT	i	16	-NONE-	in
代	NT	i	17	ROOT	out
初	LC	b	18	ROOT	out
引	VV	b	31	ROOT	out
进	VV	i	18	-NONE-	in
日	NR	b	21	-NONE-	in
本	NR	i	29	ROOT	out
东	NR	b	23	-NONE-	in
洋	NR	i	29	ROOT	out
纺	NN	b	29	ROOT	out
织	NN	i	24	-NONE-	in
技	NN	b	27	-NONE-	in
术	NN	i	29	ROOT	out
和	CC	b	29	ROOT	out
设	NN	b	18	ROOT	out
备	NN	i	29	-NONE-	in
的	DEC	b	39	ROOT	out
一	CD	b	33	ROOT	out
家	M	b	39	ROOT	out
苏	NR	b	35	ROOT	out
港	NR	b	39	ROOT	out
合	JJ	b	39	ROOT	out
资	JJ	i	36	-NONE-	in
企	NN	b	39	-NONE-	in
业	NN	i	12	ROOT	out
，	PU	b	12	ROOT	out
前	DT	b	43	ROOT	out
两	CD	b	43	ROOT	out
期	M	b	45	ROOT	out
工	NN	b	45	-NONE-	in
程	NN	i	46	ROOT	out
建	VV	b	52	ROOT	out
成	VV	i	46	-NONE-	in
并	CC	b	46	ROOT	out
投	VV	b	46	ROOT	out
产	VV	i	49	-NONE-	in
以	LC	b	52	-NONE-	in
来	LC	i	58	ROOT	out
，	PU	b	58	ROOT	out
已	AD	b	58	ROOT	out
累	AD	b	56	-NONE-	in
计	AD	i	58	ROOT	out
实	VV	b	58	-NONE-	in
现	VV	i	12	ROOT	out
利	NN	b	60	-NONE-	in
润	NN	i	58	ROOT	out
一	CD	b	62	-NONE-	in
点	CD	i	63	-NONE-	in
四	CD	i	64	-NONE-	in
七	CD	i	65	-NONE-	in
亿	CD	i	66	ROOT	out
元	M	b	58	ROOT	out
，	PU	b	12	ROOT	out
跻	VV	b	12	ROOT	out
身	VV	i	68	-NONE-	in
于	P	b	68	ROOT	out
国	NN	b	72	-NONE-	in
家	NN	i	78	ROOT	out
二	CD	b	74	ROOT	out
类	M	b	78	ROOT	out
大	JJ	b	76	-NONE-	in
型	JJ	i	78	ROOT	out
企	NN	b	78	-NONE-	in
业	NN	i	80	ROOT	out
行	NN	b	80	-NONE-	in
列	NN	i	70	ROOT	out
。	PU	b	12	ROOT	out

这	DT	b	1	ROOT	out
次	M	b	8	ROOT	out
新	AD	b	3	ROOT	out
投	VV	b	5	ROOT	out
产	VV	i	3	-NONE-	in
的	DEC	b	8	ROOT	out
生	NN	b	8	-NONE-	in
产	NN	i	6	-NONE-	in
线	NN	i	16	ROOT	out
，	PU	b	16	ROOT	out
由	P	b	16	ROOT	out
该	DT	b	13	ROOT	out
公	NN	b	13	-NONE-	in
司	NN	i	10	ROOT	out
自	AD	b	15	-NONE-	in
行	AD	i	16	ROOT	out
设	VV	b	-1	ROOT	out
计	VV	i	16	-NONE-	in
，	PU	b	16	ROOT	out
自	AD	b	20	-NONE-	in
行	AD	i	21	ROOT	out
开	VV	b	16	ROOT	out
发	VV	i	21	-NONE-	in
，	PU	b	16	ROOT	out
自	AD	b	25	-NONE-	in
行	AD	i	26	ROOT	out
调	VV	b	16	ROOT	out
试	VV	i	26	-NONE-	in
。	PU	b	16	ROOT	out

设	NN	b	9	ROOT	out
备	NN	i	0	-NONE-	in
从	P	b	9	ROOT	out
安	NN	b	2	ROOT	out
装	NN	i	3	-NONE-	in
到	P	b	2	ROOT	out
投	NN	b	5	ROOT	out
产	NN	i	6	-NONE-	in
只	AD	b	9	ROOT	out
用	VV	b	17	ROOT	out
了	AS	b	9	ROOT	out
三	CD	b	12	ROOT	out
个	M	b	13	ROOT	out
月	NN	b	15	ROOT	out
时	NN	b	15	-NONE-	in
间	NN	i	9	ROOT	out
，	PU	b	17	ROOT	out
开	VV	b	-1	ROOT	out
发	VV	i	17	-NONE-	in
了	AS	b	17	ROOT	out
企	NN	b	21	-NONE-	in
业	NN	i	24	ROOT	out
自	PN	b	23	-NONE-	in
己	PN	i	21	ROOT	out
的	DEG	b	28	ROOT	out
专	NN	b	26	-NONE-	in
利	NN	i	28	ROOT	out
技	NN	b	28	-NONE-	in
术	NN	i	17	ROOT	out
，	PU	b	17	ROOT	out
为	P	b	47	ROOT	out
公	NN	b	32	-NONE-	in
司	NN	i	38	ROOT	out
下	AD	b	35	-NONE-	in
一	AD	i	35	-NONE-	in
步	AD	i	38	ROOT	out
对	P	b	38	ROOT	out
外	NN	b	36	ROOT	out
输	VV	b	30	ROOT	out
出	VV	i	38	-NONE-	in
氨	NN	b	41	-NONE-	in
伦	NN	i	42	-NONE-	in
丝	NN	i	46	ROOT	out
生	NN	b	46	ROOT	out
产	NN	i	43	-NONE-	in
技	NN	b	46	-NONE-	in
术	NN	i	38	ROOT	out
奠	VV	b	17	ROOT	out
定	VV	i	47	-NONE-	in
了	AS	b	47	ROOT	out
基	NN	b	51	-NONE-	in
础	NN	i	47	ROOT	out
。	PU	b	17	ROOT	out

（	PU	b	1	ROOT	out
完	VV	b	-1	ROOT	out
）	PU	b	1	ROOT	out

中	NR	b	1	-NONE-	in
国	NR	i	2	ROOT	out
鼓	VV	b	-1	ROOT	out
励	VV	i	2	-NONE-	in
民	JJ	b	5	-NONE-	in
营	JJ	i	8	ROOT	out
企	NN	b	7	-NONE-	in
业	NN	i	8	-NONE-	in
家	NN	i	2	ROOT	out
投	VV	b	2	ROOT	out
资	VV	i	9	-NONE-	in
国	NN	b	12	-NONE-	in
家	NN	i	15	ROOT	out
基	NN	b	14	-NONE-	in
础	NN	i	15	ROOT	out
建	NN	b	9	ROOT	out
设	NN	i	15	-NONE-	in

新	NN	b	1	-NONE-	in
华	NN	i	2	-NONE-	in
社	NN	i	22	ROOT	out
南	NR	b	4	-NONE-	in
昌	NR	i	22	ROOT	out
十	NT	b	6	-NONE-	in
二	NT	i	7	-NONE-	in
月	NT	i	22	ROOT	out
七	NT	b	9	-NONE-	in
日	NT	i	22	ROOT	out
电	NN	b	22	ROOT	out
（	PU	b	22	ROOT	out
记	NN	b	13	-NONE-	in
者	NN	i	22	ROOT	out
蒋	NR	b	16	-NONE-	in
秋	NR	i	16	-NONE-	in
生	NR	i	22	ROOT	out
、	PU	b	22	ROOT	out
李	NR	b	19	-NONE-	in
平	NR	i	22	ROOT	out
、	PU	b	22	ROOT	out
刘	NR	b	22	-NONE-	in
义	NR	i	-1	ROOT	out
）	PU	b	22	ROOT	out

地	VV	b	10	ROOT	out
处	VV	i	0	-NONE-	in
世	NN	b	3	-NONE-	in
界	NN	i	5	ROOT	out
名	NN	b	5	-NONE-	in
山	NN	i	7	ROOT	out
庐	NR	b	7	-NONE-	in
山	NR	i	8	ROOT	out
脚	NN	b	9	ROOT	out
下	LC	b	0	ROOT	out
的	DEC	b	20	ROOT	out
九	NR	b	12	-NONE-	in
江	NR	i	20	ROOT	out
民	NN	b	14	-NONE-	in
生	NN	i	16	ROOT	out
集	NN	b	16	-NONE-	in
团	NN	i	20	ROOT	out
有	JJ	b	20	ROOT	out
限	JJ	i	17	-NONE-	in
公	NN	b	20	-NONE-	in
司	NN	i	22	ROOT	out
，	PU	b	22	ROOT	out
是	VC	b	-1	ROOT	out
跻	VV	b	22	ROOT	out
身	VV	i	23	-NONE-	in
中	NR	b	26	-NONE-	in
国	NR	i	35	ROOT	out
五	CD	b	28	-NONE-	in
百	CD	i	29	ROOT	out
家	M	b	35	ROOT	out
最	JJ	b	31	-NONE-	in
大	JJ	i	35	ROOT	out
私	JJ	b	33	-NONE-	in
营	JJ	i	35	ROOT	out
企	NN	b	35	-NONE-	in
业	NN	i	23	ROOT	out
。	PU	b	22	ROOT	out

身	VV	b	1	-NONE-	in
兼	VV	i	26	ROOT	out
全	DT	b	3	ROOT	out
国	NN	b	5	ROOT	out
政	NN	b	5	-NONE-	in
协	NN	i	7	ROOT	out
委	NN	b	7	-NONE-	in
员	NN	i	22	ROOT	out
、	PU	b	22	ROOT	out
江	NR	b	10	-NONE-	in
西	NR	i	11	-NONE-	in
省	NR	i	13	ROOT	out
政	NN	b	13	-NONE-	in
协	NN	i	15	ROOT	out
常	NN	b	15	-NONE-	in
委	NN	i	22	ROOT	out
、	PU	b	22	ROOT	out
集	NN	b	18	-NONE-	in
团	NN	i	22	ROOT	out
公	NN	b	20	-NONE-	in
司	NN	i	22	ROOT	out
总	NN	b	22	-NONE-	in
裁	NN	i	25	ROOT	out
等	ETC	b	22	ROOT	out
多	CD	b	25	ROOT	out
职	NN	b	1	ROOT	out
的	DEC	b	28	ROOT	out
王	NR	b	28	-NONE-	in
翔	NR	i	57	ROOT	out
，	PU	b	57	ROOT	out
在	P	b	57	ROOT	out
谈	VV	b	50	ROOT	out
到	VV	i	31	-NONE-	in
近	AD	b	35	ROOT	out
几	CD	b	35	ROOT	out
年	M	b	38	ROOT	out
大	AD	b	37	-NONE-	in
量	AD	i	38	ROOT	out
投	VV	b	31	ROOT	out
资	VV	i	38	-NONE-	in
国	NN	b	41	-NONE-	in
家	NN	i	44	ROOT	out
基	NN	b	43	-NONE-	in
础	NN	i	44	ROOT	out
建	NN	b	38	ROOT	out
设	NN	i	44	-NONE-	in
取	VV	b	38	ROOT	out
得	VV	i	46	-NONE-	in
成	NN	b	46	ROOT	out
效	NN	i	48	-NONE-	in
时	LC	b	30	ROOT	out
，	PU	b	57	ROOT	out
实	VA	b	56	ROOT	out
实	VA	i	52	-NONE-	in
在	VA	i	52	-NONE-	in
在	VA	i	54	-NONE-	in
地	DEV	b	57	ROOT	out
告	VV	b	-1	ROOT	out
诉	VV	i	57	-NONE-	in
记	NN	b	60	-NONE-	in
者	NN	i	57	ROOT	out
：	PU	b	57	ROOT	out
“	PU	b	82	ROOT	out
立	VV	b	82	ROOT	out
足	VV	i	63	-NONE-	in
内	NN	b	66	-NONE-	in
地	NN	i	63	ROOT	out
，	PU	b	63	ROOT	out
为	P	b	78	ROOT	out
当	NN	b	70	-NONE-	in
地	NN	i	73	ROOT	out
经	NN	b	72	-NONE-	in
济	NN	i	73	ROOT	out
发	NN	b	68	ROOT	out
展	NN	i	73	-NONE-	in
‘	PU	b	78	ROOT	out
修	VV	b	78	ROOT	out
桥	VV	i	76	-NONE-	in
铺	VV	b	63	ROOT	out
路	VV	i	78	-NONE-	in
’	PU	b	78	ROOT	out
，	PU	b	82	ROOT	out
是	VC	b	57	ROOT	out
我	PN	b	87	ROOT	out
明	VA	b	85	-NONE-	in
智	VA	i	86	ROOT	out
的	DEC	b	87	ROOT	out
选	NN	b	82	ROOT	out
择	NN	i	87	-NONE-	in
。	PU	b	57	ROOT	out
”	PU	b	57	ROOT	out

王	NR	b	1	-NONE-	in
翔	NR	i	4	ROOT	out
虽	CS	b	4	ROOT	out
年	VV	b	4	-NONE-	in
过	VV	i	22	ROOT	out
半	VV	i	6	-NONE-	in
百	VV	i	4	-NONE-	in
，	PU	b	22	ROOT	out
但	AD	b	22	ROOT	out
其	PN	b	20	ROOT	out
充	VA	b	12	ROOT	out
沛	VA	i	10	-NONE-	in
的	DEC	b	14	ROOT	out
精	NN	b	14	-NONE-	in
力	NN	i	20	ROOT	out
和	CC	b	20	ROOT	out
敏	VA	b	18	ROOT	out
捷	VA	i	16	-NONE-	in
的	DEC	b	20	ROOT	out
思	NN	b	20	-NONE-	in
维	NN	i	22	ROOT	out
，	PU	b	22	ROOT	out
给	VV	b	-1	ROOT	out
人	NN	b	22	ROOT	out
以	P	b	22	ROOT	out
一	CD	b	26	ROOT	out
个	M	b	29	ROOT	out
挑	NN	b	29	-NONE-	in
战	NN	i	27	-NONE-	in
者	NN	i	30	ROOT	out
的	DEG	b	32	ROOT	out
印	NN	b	32	-NONE-	in
象	NN	i	24	ROOT	out
。	PU	b	22	ROOT	out

民	NN	b	1	-NONE-	in
生	NN	i	3	ROOT	out
集	NN	b	3	-NONE-	in
团	NN	i	17	ROOT	out
近	AD	b	6	ROOT	out
两	CD	b	6	ROOT	out
年	M	b	17	ROOT	out
为	P	b	17	ROOT	out
改	VV	b	7	ROOT	out
善	VV	i	8	-NONE-	in
九	NR	b	11	-NONE-	in
江	NR	i	14	ROOT	out
基	NN	b	13	-NONE-	in
础	NN	i	14	ROOT	out
设	NN	b	8	ROOT	out
施	NN	i	14	-NONE-	in
所	MSP	b	17	ROOT	out
做	VV	b	18	ROOT	out
的	DEC	b	19	ROOT	out
贡	NN	b	25	ROOT	out
献	NN	i	19	-NONE-	in
，	PU	b	25	ROOT	out
在	P	b	25	ROOT	out
九	NR	b	24	-NONE-	in
江	NR	i	22	ROOT	out
无	VV	b	-1	ROOT	out
人	VV	i	25	-NONE-	in
不	VV	i	28	-NONE-	in
晓	VV	i	25	-NONE-	in
。	PU	b	25	ROOT	out

九	NR	b	1	-NONE-	in
江	NR	i	2	ROOT	out
是	VC	b	-1	ROOT	out
江	NR	b	4	-NONE-	in
西	NR	i	5	ROOT	out
的	DEG	b	8	ROOT	out
北	NN	b	8	ROOT	out
大	NN	b	8	-NONE-	in
门	NN	i	2	ROOT	out
，	PU	b	2	ROOT	out
是	VC	b	2	ROOT	out
沿	P	b	16	ROOT	out
长	NR	b	13	-NONE-	in
江	NR	i	11	ROOT	out
开	VV	b	16	ROOT	out
放	VV	i	14	-NONE-	in
开	VV	b	18	ROOT	out
发	VV	i	16	-NONE-	in
的	DEC	b	24	ROOT	out
重	NN	b	20	-NONE-	in
点	NN	i	24	ROOT	out
城	NN	b	22	-NONE-	in
市	NN	i	24	ROOT	out
之	NN	b	24	-NONE-	in
一	NN	i	10	ROOT	out
。	PU	b	2	ROOT	out

王	NR	b	1	-NONE-	in
翔	NR	i	2	ROOT	out
投	VV	b	-1	ROOT	out
巨	NN	b	4	-NONE-	in
资	NN	i	2	ROOT	out
一	CD	b	6	-NONE-	in
点	CD	i	7	-NONE-	in
二	CD	i	8	-NONE-	in
七	CD	i	9	-NONE-	in
亿	CD	i	10	ROOT	out
元	M	b	13	ROOT	out
人	NN	b	12	-NONE-	in
民	NN	i	13	-NONE-	in
币	NN	i	2	ROOT	out
参	VV	b	2	ROOT	out
与	VV	i	14	-NONE-	in
了	AS	b	14	ROOT	out
九	NR	b	18	-NONE-	in
江	NR	i	21	ROOT	out
火	NN	b	20	-NONE-	in
车	NN	i	21	-NONE-	in
站	NN	i	23	ROOT	out
站	NN	b	23	-NONE-	in
场	NN	i	24	ROOT	out
的	DEG	b	25	ROOT	out
建	NN	b	14	ROOT	out
设	NN	i	25	-NONE-	in
。	PU	b	2	ROOT	out

江	NR	b	2	-NONE-	in
泽	NR	i	2	-NONE-	in
民	NR	i	4	ROOT	out
主	NN	b	4	-NONE-	in
席	NN	i	11	ROOT	out
在	P	b	8	ROOT	out
九	NR	b	7	-NONE-	in
江	NR	i	5	ROOT	out
视	VV	b	10	ROOT	out
察	VV	i	8	-NONE-	in
时	LC	b	11	ROOT	out
说	VV	b	-1	ROOT	out
：	PU	b	11	ROOT	out
“	PU	b	11	ROOT	out
九	NR	b	15	-NONE-	in
江	NR	i	16	ROOT	out
地	VV	b	34	ROOT	out
处	VV	i	16	-NONE-	in
京	NR	b	19	-NONE-	in
九	NR	i	21	ROOT	out
中	NN	b	21	-NONE-	in
段	NN	i	16	ROOT	out
，	PU	b	34	ROOT	out
地	NN	b	24	-NONE-	in
理	NN	i	26	ROOT	out
位	NN	b	26	-NONE-	in
置	NN	i	28	ROOT	out
很	AD	b	28	ROOT	out
好	VA	b	34	ROOT	out
，	PU	b	34	ROOT	out
九	NR	b	31	-NONE-	in
江	NR	i	34	ROOT	out
前	VV	b	33	-NONE-	in
途	VV	i	34	-NONE-	in
无	VV	i	11	ROOT	out
量	VV	i	34	-NONE-	in
。	PU	b	11	ROOT	out
”	PU	b	11	ROOT	out

并	AD	b	7	ROOT	out
亲	AD	b	7	ROOT	out
笔	AD	i	1	-NONE-	in
为	P	b	7	ROOT	out
九	NN	b	5	-NONE-	in
江	NN	i	6	-NONE-	in
站	NN	i	3	ROOT	out
题	VV	b	-1	ROOT	out
写	VV	i	7	-NONE-	in
了	AS	b	7	ROOT	out
站	NN	b	11	-NONE-	in
名	NN	i	7	ROOT	out
。	PU	b	7	ROOT	out

九	NR	b	1	-NONE-	in
江	NR	i	2	ROOT	out
是	VC	b	-1	ROOT	out
连	VV	b	9	ROOT	out
接	VV	i	3	-NONE-	in
长	NR	b	6	-NONE-	in
江	NR	i	8	ROOT	out
南	NN	b	8	-NONE-	in
北	NN	i	3	ROOT	out
的	DEC	b	11	ROOT	out
要	NN	b	11	-NONE-	in
道	NN	i	2	ROOT	out
。	PU	b	2	ROOT	out

但	AD	b	21	ROOT	out
每	DT	b	2	ROOT	out
年	M	b	3	ROOT	out
的	DEG	b	5	ROOT	out
汛	NN	b	5	-NONE-	in
期	NN	i	21	ROOT	out
给	P	b	21	ROOT	out
当	NN	b	8	-NONE-	in
地	NN	i	11	ROOT	out
经	NN	b	10	-NONE-	in
济	NN	i	11	ROOT	out
建	NN	b	18	ROOT	out
设	NN	i	11	-NONE-	in
和	CC	b	18	ROOT	out
老	NN	b	16	-NONE-	in
百	NN	i	16	-NONE-	in
姓	NN	i	17	ROOT	out
的	DEG	b	18	ROOT	out
生	NN	b	6	ROOT	out
活	NN	i	18	-NONE-	in
都	AD	b	21	ROOT	out
造	VV	b	82	ROOT	out
成	VV	i	21	-NONE-	in
了	AS	b	21	ROOT	out
一	JJ	b	25	-NONE-	in
定	JJ	i	26	ROOT	out
的	DEG	b	28	ROOT	out
影	NN	b	28	-NONE-	in
响	NN	i	21	ROOT	out
，	PU	b	82	ROOT	out
特	AD	b	32	-NONE-	in
别	AD	i	30	-NONE-	in
是	AD	i	43	ROOT	out
九	NR	b	34	-NONE-	in
江	NR	i	35	-NONE-	in
市	NR	i	36	ROOT	out
的	DEG	b	42	ROOT	out
龙	NR	b	38	-NONE-	in
开	NR	i	39	-NONE-	in
河	NR	i	42	ROOT	out
下	NN	b	41	-NONE-	in
游	NN	i	42	-NONE-	in
段	NN	i	43	ROOT	out
处	VV	b	82	ROOT	out
在	P	b	43	ROOT	out
市	NN	b	46	-NONE-	in
区	NN	i	47	ROOT	out
的	DEG	b	52	ROOT	out
中	NN	b	49	-NONE-	in
轴	NN	i	50	-NONE-	in
线	NN	i	52	ROOT	out
位	NN	b	52	-NONE-	in
置	NN	i	53	ROOT	out
上	LC	b	44	ROOT	out
，	PU	b	82	ROOT	out
其	PN	b	57	ROOT	out
水	NN	b	57	-NONE-	in
流	NN	i	58	ROOT	out
穿	VV	b	82	ROOT	out
城	NN	b	60	-NONE-	in
区	NN	i	58	ROOT	out
注	VV	b	58	ROOT	out
入	VV	i	61	-NONE-	in
长	NR	b	64	-NONE-	in
江	NR	i	61	ROOT	out
，	PU	b	82	ROOT	out
所	AD	b	67	-NONE-	in
以	AD	i	79	ROOT	out
一	AD	b	69	ROOT	out
到	VV	b	79	ROOT	out
汛	NN	b	71	-NONE-	in
期	NN	i	69	ROOT	out
，	PU	b	79	ROOT	out
上	VV	b	74	-NONE-	in
涨	VV	i	75	ROOT	out
的	DEC	b	78	ROOT	out
长	NR	b	77	-NONE-	in
江	NR	i	78	ROOT	out
水	NN	b	79	ROOT	out
倒	VV	b	82	ROOT	out
灌	VV	i	79	-NONE-	in
，	PU	b	82	ROOT	out
使	VV	b	-1	ROOT	out
龙	NR	b	84	-NONE-	in
开	NR	i	85	-NONE-	in
河	NR	i	88	ROOT	out
下	NN	b	87	-NONE-	in
游	NN	i	88	-NONE-	in
段	NN	i	82	ROOT	out
成	VV	b	82	ROOT	out
了	AS	b	89	ROOT	out
历	NT	b	92	-NONE-	in
年	NT	i	95	ROOT	out
紧	AD	b	95	ROOT	out
张	AD	i	93	-NONE-	in
抗	VV	b	97	ROOT	out
洪	VV	i	95	-NONE-	in
的	DEC	b	99	ROOT	out
战	NN	b	99	-NONE-	in
场	NN	i	89	ROOT	out
。	PU	b	82	ROOT	out

为	P	b	18	ROOT	out
此	PN	b	0	ROOT	out
，	PU	b	18	ROOT	out
省	NN	b	5	ROOT	out
政	NN	b	5	-NONE-	in
府	NN	i	18	ROOT	out
将	BA	b	18	ROOT	out
“	PU	b	16	ROOT	out
龙	NR	b	9	-NONE-	in
开	NR	i	10	-NONE-	in
河	NR	i	16	ROOT	out
治	NN	b	16	ROOT	out
理	NN	i	11	-NONE-	in
开	NN	b	16	ROOT	out
发	NN	i	13	-NONE-	in
工	NN	b	16	-NONE-	in
程	NN	i	18	ROOT	out
”	PU	b	16	ROOT	out
纳	VV	b	-1	ROOT	out
入	VV	i	18	-NONE-	in
了	AS	b	18	ROOT	out
省	NN	b	27	ROOT	out
重	NN	b	23	-NONE-	in
点	NN	i	27	ROOT	out
防	NN	b	27	ROOT	out
洪	NN	i	24	-NONE-	in
工	NN	b	27	-NONE-	in
程	NN	i	18	ROOT	out
。	PU	b	18	ROOT	out

王	NR	b	1	-NONE-	in
翔	NR	i	7	ROOT	out
得	VV	b	4	ROOT	out
知	VV	i	2	-NONE-	in
后	LC	b	7	ROOT	out
立	AD	b	6	-NONE-	in
即	AD	i	7	ROOT	out
请	VV	b	-1	ROOT	out
专	NN	b	9	-NONE-	in
家	NN	i	7	ROOT	out
论	VV	b	7	ROOT	out
证	VV	i	10	-NONE-	in
。	PU	b	7	ROOT	out

他	PN	b	1	ROOT	out
说	VV	b	-1	ROOT	out
，	PU	b	1	ROOT	out
这	PN	b	4	ROOT	out
是	VC	b	28	ROOT	out
一	CD	b	6	ROOT	out
项	M	b	13	ROOT	out
施	VV	b	11	ROOT	out
泽	VV	i	7	-NONE-	in
后	VV	i	10	-NONE-	in
世	VV	i	7	-NONE-	in
的	DEC	b	13	ROOT	out
工	NN	b	13	-NONE-	in
程	NN	i	4	ROOT	out
，	PU	b	4	ROOT	out
也	AD	b	16	ROOT	out
是	VC	b	4	ROOT	out
政	NN	b	18	-NONE-	in
府	NN	i	22	ROOT	out
最	AD	b	22	ROOT	out
急	AD	b	21	-NONE-	in
切	AD	i	22	ROOT	out
要	VV	b	24	ROOT	out
办	VV	b	22	ROOT	out
的	DEC	b	25	ROOT	out
事	NN	b	16	ROOT	out
，	PU	b	28	ROOT	out
我	PN	b	28	ROOT	out
有	VE	b	1	ROOT	out
责	NN	b	28	ROOT	out
任	NN	i	29	-NONE-	in
尽	VV	b	28	ROOT	out
一	CD	b	33	ROOT	out
份	M	b	34	ROOT	out
力	NN	b	31	ROOT	out
。	PU	b	1	ROOT	out

王	NR	b	1	-NONE-	in
翔	NR	i	2	ROOT	out
举	VV	b	-1	ROOT	out
全	NN	b	4	-NONE-	in
力	NN	i	2	ROOT	out
投	VV	b	2	ROOT	out
资	VV	i	5	-NONE-	in
一	CD	b	8	-NONE-	in
点	CD	i	9	-NONE-	in
二	CD	i	10	-NONE-	in
亿	CD	i	11	ROOT	out
元	M	b	14	ROOT	out
人	NN	b	13	-NONE-	in
民	NN	i	14	-NONE-	in
币	NN	i	5	ROOT	out
兴	VV	b	16	-NONE-	in
建	VV	i	2	ROOT	out
防	NN	b	20	ROOT	out
洪	NN	i	17	-NONE-	in
工	NN	b	20	-NONE-	in
程	NN	i	16	ROOT	out
。	PU	b	2	ROOT	out

在	P	b	11	ROOT	out
今	NT	b	2	-NONE-	in
年	NT	i	3	ROOT	out
的	DEG	b	4	ROOT	out
防	NN	b	6	ROOT	out
汛	NN	i	4	-NONE-	in
中	LC	b	0	ROOT	out
这	DT	b	8	ROOT	out
项	M	b	10	ROOT	out
工	NN	b	10	-NONE-	in
程	NN	i	11	ROOT	out
显	VV	b	-1	ROOT	out
示	VV	i	11	-NONE-	in
出	VV	b	11	ROOT	out
了	AS	b	11	ROOT	out
巨	VA	b	17	ROOT	out
大	VA	i	15	-NONE-	in
的	DEC	b	19	ROOT	out
威	NN	b	19	-NONE-	in
力	NN	i	11	ROOT	out
。	PU	b	11	ROOT	out

目	NT	b	1	-NONE-	in
前	NT	i	6	ROOT	out
，	PU	b	6	ROOT	out
王	NR	b	4	-NONE-	in
翔	NR	i	6	ROOT	out
又	AD	b	6	ROOT	out
开	VV	b	-1	ROOT	out
始	VV	i	6	-NONE-	in
了	AS	b	6	ROOT	out
九	NR	b	10	-NONE-	in
龙	NR	i	11	-NONE-	in
街	NR	i	12	ROOT	out
的	DEG	b	13	ROOT	out
建	NN	b	6	ROOT	out
设	NN	i	13	-NONE-	in
。	PU	b	6	ROOT	out

与	P	b	3	ROOT	out
此	PN	b	0	ROOT	out
同	NN	b	3	-NONE-	in
时	NN	i	19	ROOT	out
，	PU	b	19	ROOT	out
为	P	b	19	ROOT	out
改	VV	b	5	ROOT	out
善	VV	i	6	-NONE-	in
九	NR	b	9	-NONE-	in
江	NR	i	10	ROOT	out
的	DEG	b	14	ROOT	out
投	NN	b	14	ROOT	out
资	NN	i	11	-NONE-	in
环	NN	b	14	-NONE-	in
境	NN	i	6	ROOT	out
，	PU	b	19	ROOT	out
王	NR	b	17	-NONE-	in
翔	NR	i	19	ROOT	out
决	VV	b	19	-NONE-	in
定	VV	i	-1	ROOT	out
投	VV	b	19	ROOT	out
资	VV	i	20	-NONE-	in
数	CD	b	23	-NONE-	in
亿	CD	i	24	ROOT	out
元	M	b	20	ROOT	out
在	P	b	32	ROOT	out
九	NR	b	27	-NONE-	in
江	NR	i	29	ROOT	out
市	NN	b	29	-NONE-	in
区	NN	i	25	ROOT	out
开	VV	b	32	ROOT	out
发	VV	i	30	-NONE-	in
建	VV	b	20	ROOT	out
设	VV	i	32	-NONE-	in
与	P	b	42	ROOT	out
世	NN	b	36	-NONE-	in
界	NN	i	38	ROOT	out
名	NN	b	38	-NONE-	in
山	NN	i	40	ROOT	out
庐	NR	b	40	-NONE-	in
山	NR	i	34	ROOT	out
相	AD	b	42	ROOT	out
呼	VV	b	44	ROOT	out
应	VV	i	42	-NONE-	in
的	DEC	b	52	ROOT	out
“	PU	b	52	ROOT	out
大	NN	b	47	-NONE-	in
千	NN	i	49	-NONE-	in
世	NN	i	49	-NONE-	in
界	NN	i	52	ROOT	out
游	NN	b	51	-NONE-	in
乐	NN	i	52	-NONE-	in
园	NN	i	32	ROOT	out
”	PU	b	52	ROOT	out
。	PU	b	19	ROOT	out

王	NR	b	1	-NONE-	in
翔	NR	i	2	ROOT	out
投	VV	b	17	ROOT	out
资	VV	i	2	-NONE-	in
国	NN	b	5	-NONE-	in
家	NN	i	10	ROOT	out
基	NN	b	7	-NONE-	in
础	NN	i	10	ROOT	out
设	NN	b	10	ROOT	out
施	NN	i	8	-NONE-	in
建	NN	b	2	ROOT	out
设	NN	i	10	-NONE-	in
，	PU	b	17	ROOT	out
利	VV	b	17	ROOT	out
国	VV	i	13	-NONE-	in
利	VV	b	17	ROOT	out
民	VV	i	15	-NONE-	in
利	VV	b	-1	ROOT	out
己	VV	i	17	-NONE-	in
。	PU	b	17	ROOT	out


