上	NR	b	1	-NONE-	in
海	NR	i	3	ROOT	out
浦	NR	b	3	-NONE-	in
东	NR	i	9	ROOT	out
开	NN	b	9	ROOT	out
发	NN	i	4	-NONE-	in
与	CC	b	9	ROOT	out
法	NN	b	8	-NONE-	in
制	NN	i	9	ROOT	out
建	NN	b	12	ROOT	out
设	NN	i	9	-NONE-	in
同	VV	b	12	-NONE-	in
步	VV	i	-1	ROOT	out

新	NN	b	1	-NONE-	in
华	NN	i	2	-NONE-	in
社	NN	i	19	ROOT	out
上	NR	b	4	-NONE-	in
海	NR	i	19	ROOT	out
二	NT	b	6	-NONE-	in
月	NT	i	19	ROOT	out
十	NT	b	8	-NONE-	in
日	NT	i	19	ROOT	out
电	NN	b	19	ROOT	out
（	PU	b	19	ROOT	out
记	NN	b	12	-NONE-	in
者	NN	i	19	ROOT	out
谢	NR	b	15	-NONE-	in
金	NR	i	15	-NONE-	in
虎	NR	i	19	ROOT	out
、	PU	b	19	ROOT	out
张	NR	b	19	-NONE-	in
持	NR	i	19	-NONE-	in
坚	NR	i	-1	ROOT	out
）	PU	b	19	ROOT	out

上	NR	b	1	-NONE-	in
海	NR	i	3	ROOT	out
浦	NR	b	3	-NONE-	in
东	NR	i	10	ROOT	out
近	NT	b	5	-NONE-	in
年	NT	i	6	ROOT	out
来	LC	b	10	ROOT	out
颁	VV	b	10	ROOT	out
布	VV	i	7	-NONE-	in
实	VV	b	10	-NONE-	in
行	VV	i	-1	ROOT	out
了	AS	b	10	ROOT	out
涉	VV	b	34	ROOT	out
及	VV	i	12	-NONE-	in
经	NN	b	15	-NONE-	in
济	NN	i	30	ROOT	out
、	PU	b	30	ROOT	out
贸	NN	b	18	-NONE-	in
易	NN	i	30	ROOT	out
、	PU	b	30	ROOT	out
建	NN	b	30	ROOT	out
设	NN	i	20	-NONE-	in
、	PU	b	30	ROOT	out
规	NN	b	24	-NONE-	in
划	NN	i	30	ROOT	out
、	PU	b	30	ROOT	out
科	NN	b	27	-NONE-	in
技	NN	i	30	ROOT	out
、	PU	b	30	ROOT	out
文	NN	b	30	-NONE-	in
教	NN	i	33	ROOT	out
等	ETC	b	30	ROOT	out
领	NN	b	33	-NONE-	in
域	NN	i	12	ROOT	out
的	DEC	b	43	ROOT	out
七	CD	b	36	-NONE-	in
十	CD	i	37	-NONE-	in
一	CD	i	38	ROOT	out
件	M	b	43	ROOT	out
法	NN	b	40	-NONE-	in
规	NN	i	41	-NONE-	in
性	NN	i	43	ROOT	out
文	NN	b	43	-NONE-	in
件	NN	i	10	ROOT	out
，	PU	b	10	ROOT	out
确	VV	b	10	ROOT	out
保	VV	i	45	-NONE-	in
了	AS	b	45	ROOT	out
浦	NR	b	49	-NONE-	in
东	NR	i	50	ROOT	out
开	NN	b	52	ROOT	out
发	NN	i	50	-NONE-	in
的	DEG	b	55	ROOT	out
有	JJ	b	55	ROOT	out
序	JJ	i	53	-NONE-	in
进	NN	b	45	ROOT	out
行	NN	i	55	-NONE-	in
。	PU	b	10	ROOT	out

浦	NR	b	1	-NONE-	in
东	NR	i	4	ROOT	out
开	NN	b	4	ROOT	out
发	NN	i	2	-NONE-	in
开	NN	b	6	ROOT	out
放	NN	i	4	-NONE-	in
是	VC	b	43	ROOT	out
一	CD	b	8	ROOT	out
项	M	b	34	ROOT	out
振	VV	b	29	ROOT	out
兴	VV	i	9	-NONE-	in
上	NR	b	12	-NONE-	in
海	NR	i	9	ROOT	out
，	PU	b	9	ROOT	out
建	VV	b	9	ROOT	out
设	VV	i	14	-NONE-	in
现	NN	b	17	-NONE-	in
代	NN	i	18	-NONE-	in
化	NN	i	28	ROOT	out
经	NN	b	20	-NONE-	in
济	NN	i	26	ROOT	out
、	PU	b	26	ROOT	out
贸	NN	b	23	-NONE-	in
易	NN	i	26	ROOT	out
、	PU	b	26	ROOT	out
金	NN	b	26	-NONE-	in
融	NN	i	28	ROOT	out
中	NN	b	28	-NONE-	in
心	NN	i	14	ROOT	out
的	DEC	b	34	ROOT	out
跨	JJ	b	34	ROOT	out
世	JJ	i	32	-NONE-	in
纪	JJ	i	30	-NONE-	in
工	NN	b	34	-NONE-	in
程	NN	i	6	ROOT	out
，	PU	b	43	ROOT	out
因	AD	b	43	ROOT	out
此	AD	i	36	-NONE-	in
大	AD	b	39	-NONE-	in
量	AD	i	40	ROOT	out
出	VV	b	42	ROOT	out
现	VV	i	40	-NONE-	in
的	DEC	b	43	ROOT	out
是	VC	b	-1	ROOT	out
以	NT	b	45	-NONE-	in
前	NT	i	48	ROOT	out
不	AD	b	48	ROOT	out
曾	AD	b	48	ROOT	out
遇	VV	b	51	ROOT	out
到	VV	i	48	-NONE-	in
过	AS	b	48	ROOT	out
的	DEC	b	58	ROOT	out
新	JJ	b	54	ROOT	out
情	NN	b	54	-NONE-	in
况	NN	i	58	ROOT	out
、	PU	b	58	ROOT	out
新	JJ	b	58	ROOT	out
问	NN	b	58	-NONE-	in
题	NN	i	43	ROOT	out
。	PU	b	43	ROOT	out

对	P	b	6	ROOT	out
此	PN	b	0	ROOT	out
，	PU	b	6	ROOT	out
浦	NR	b	4	-NONE-	in
东	NR	i	6	ROOT	out
不	AD	b	6	ROOT	out
是	VC	b	-1	ROOT	out
简	VA	b	8	-NONE-	in
单	VA	i	9	ROOT	out
的	DEV	b	10	ROOT	out
采	VV	b	6	ROOT	out
取	VV	i	10	-NONE-	in
“	PU	b	13	ROOT	out
干	VV	b	35	ROOT	out
一	CD	b	15	ROOT	out
段	M	b	17	ROOT	out
时	NN	b	17	-NONE-	in
间	NN	i	13	ROOT	out
，	PU	b	13	ROOT	out
等	P	b	28	ROOT	out
积	VV	b	26	ROOT	out
累	VV	i	20	-NONE-	in
了	AS	b	20	ROOT	out
经	NN	b	20	ROOT	out
验	NN	i	23	-NONE-	in
以	LC	b	26	-NONE-	in
后	LC	i	19	ROOT	out
再	AD	b	28	ROOT	out
制	VV	b	13	ROOT	out
定	VV	i	28	-NONE-	in
法	NN	b	31	-NONE-	in
规	NN	i	33	ROOT	out
条	NN	b	33	-NONE-	in
例	NN	i	28	ROOT	out
”	PU	b	13	ROOT	out
的	DEC	b	37	ROOT	out
做	NN	b	37	-NONE-	in
法	NN	i	10	ROOT	out
，	PU	b	6	ROOT	out
而	CC	b	6	ROOT	out
是	VC	b	6	ROOT	out
借	VV	b	40	ROOT	out
鉴	VV	i	41	-NONE-	in
发	JJ	b	46	ROOT	out
达	JJ	i	43	-NONE-	in
国	NN	b	46	-NONE-	in
家	NN	i	52	ROOT	out
和	CC	b	52	ROOT	out
深	NR	b	49	-NONE-	in
圳	NR	i	52	ROOT	out
等	ETC	b	49	ROOT	out
特	NN	b	52	-NONE-	in
区	NN	i	53	ROOT	out
的	DEG	b	56	ROOT	out
经	NN	b	56	ROOT	out
验	NN	i	54	-NONE-	in
教	NN	b	41	ROOT	out
训	NN	i	56	-NONE-	in
，	PU	b	41	ROOT	out
聘	VV	b	41	ROOT	out
请	VV	i	59	-NONE-	in
国	NN	b	63	-NONE-	in
内	NN	i	63	-NONE-	in
外	NN	i	69	ROOT	out
有	JJ	b	69	ROOT	out
关	JJ	i	64	-NONE-	in
专	NN	b	67	-NONE-	in
家	NN	i	69	ROOT	out
学	NN	b	69	-NONE-	in
者	NN	i	59	ROOT	out
，	PU	b	41	ROOT	out
积	AD	b	72	-NONE-	in
极	AD	i	74	ROOT	out
、	PU	b	74	ROOT	out
及	AD	b	76	ROOT	out
时	AD	i	74	-NONE-	in
地	DEV	b	77	ROOT	out
制	VV	b	41	ROOT	out
定	VV	i	77	-NONE-	in
和	CC	b	77	ROOT	out
推	VV	b	77	ROOT	out
出	VV	i	80	-NONE-	in
法	NN	b	83	-NONE-	in
规	NN	i	84	-NONE-	in
性	NN	i	86	ROOT	out
文	NN	b	86	-NONE-	in
件	NN	i	80	ROOT	out
，	PU	b	41	ROOT	out
使	VV	b	41	ROOT	out
这	DT	b	90	-NONE-	in
些	DT	i	93	ROOT	out
经	NN	b	92	-NONE-	in
济	NN	i	93	ROOT	out
活	NN	b	88	ROOT	out
动	NN	i	93	-NONE-	in
一	AD	b	96	ROOT	out
出	VV	b	88	ROOT	out
现	VV	i	96	-NONE-	in
就	AD	b	100	ROOT	out
被	SB	b	100	ROOT	out
纳	VV	b	96	ROOT	out
入	VV	i	100	-NONE-	in
法	NN	b	103	-NONE-	in
制	NN	i	105	ROOT	out
轨	NN	b	105	-NONE-	in
道	NN	i	100	ROOT	out
。	PU	b	6	ROOT	out

去	NT	b	1	-NONE-	in
年	NT	i	2	ROOT	out
初	LC	b	7	ROOT	out
浦	NR	b	4	-NONE-	in
东	NR	i	6	ROOT	out
新	NN	b	6	-NONE-	in
区	NN	i	7	ROOT	out
诞	VV	b	9	ROOT	out
生	VV	i	7	-NONE-	in
的	DEC	b	26	ROOT	out
中	NR	b	11	-NONE-	in
国	NR	i	26	ROOT	out
第	OD	b	14	ROOT	out
一	OD	i	12	-NONE-	in
家	M	b	26	ROOT	out
医	NN	b	16	-NONE-	in
疗	NN	i	26	ROOT	out
机	NN	b	18	-NONE-	in
构	NN	i	26	ROOT	out
药	NN	b	20	-NONE-	in
品	NN	i	26	ROOT	out
采	NN	b	26	ROOT	out
购	NN	i	21	-NONE-	in
服	NN	b	26	ROOT	out
务	NN	i	23	-NONE-	in
中	NN	b	26	-NONE-	in
心	NN	i	45	ROOT	out
，	PU	b	45	ROOT	out
正	AD	b	30	ROOT	out
因	P	b	30	-NONE-	in
为	P	i	45	ROOT	out
一	AD	b	32	ROOT	out
开	VV	b	30	ROOT	out
始	VV	i	32	-NONE-	in
就	AD	b	38	ROOT	out
比	AD	b	38	ROOT	out
较	AD	i	35	-NONE-	in
规	VA	b	38	-NONE-	in
范	VA	i	32	ROOT	out
，	PU	b	45	ROOT	out
运	VV	b	42	ROOT	out
转	VV	i	40	-NONE-	in
至	VV	b	45	ROOT	out
今	VV	i	42	-NONE-	in
，	PU	b	45	ROOT	out
成	VV	b	-1	ROOT	out
交	VV	i	45	-NONE-	in
药	NN	b	48	-NONE-	in
品	NN	i	45	ROOT	out
一	CD	b	50	-NONE-	in
亿	CD	i	51	-NONE-	in
多	CD	i	52	ROOT	out
元	M	b	45	ROOT	out
，	PU	b	45	ROOT	out
没	VV	b	45	ROOT	out
有	VV	i	54	-NONE-	in
发	VV	b	54	ROOT	out
现	VV	i	56	-NONE-	in
一	CD	b	59	ROOT	out
例	M	b	61	ROOT	out
回	NN	b	61	-NONE-	in
扣	NN	i	56	ROOT	out
。	PU	b	45	ROOT	out

建	NN	b	2	ROOT	out
筑	NN	i	0	-NONE-	in
是	VC	b	20	ROOT	out
开	VV	b	7	ROOT	out
发	VV	i	3	-NONE-	in
浦	NR	b	6	-NONE-	in
东	NR	i	3	ROOT	out
的	DEC	b	14	ROOT	out
一	CD	b	9	ROOT	out
项	M	b	14	ROOT	out
主	JJ	b	11	-NONE-	in
要	JJ	i	14	ROOT	out
经	NN	b	13	-NONE-	in
济	NN	i	14	ROOT	out
活	NN	b	2	ROOT	out
动	NN	i	14	-NONE-	in
，	PU	b	20	ROOT	out
这	DT	b	18	-NONE-	in
些	DT	i	19	ROOT	out
年	M	b	20	ROOT	out
有	VE	b	-1	ROOT	out
数	CD	b	22	-NONE-	in
百	CD	i	23	ROOT	out
家	M	b	27	ROOT	out
建	NN	b	27	ROOT	out
筑	NN	i	24	-NONE-	in
公	NN	b	27	-NONE-	in
司	NN	i	36	ROOT	out
、	PU	b	36	ROOT	out
四	CD	b	30	-NONE-	in
千	CD	i	31	-NONE-	in
余	CD	i	32	ROOT	out
个	M	b	36	ROOT	out
建	NN	b	36	ROOT	out
筑	NN	i	33	-NONE-	in
工	NN	b	36	-NONE-	in
地	NN	i	37	ROOT	out
遍	VV	b	20	ROOT	out
布	VV	i	37	-NONE-	in
在	P	b	37	ROOT	out
这	DT	b	41	ROOT	out
片	M	b	43	ROOT	out
热	NN	b	43	-NONE-	in
土	NN	i	44	ROOT	out
上	LC	b	39	ROOT	out
。	PU	b	20	ROOT	out

为	P	b	47	ROOT	out
规	VV	b	2	-NONE-	in
范	VV	i	0	ROOT	out
建	NN	b	6	ROOT	out
筑	NN	i	3	-NONE-	in
行	NN	b	6	-NONE-	in
为	NN	i	2	ROOT	out
，	PU	b	2	ROOT	out
防	VV	b	2	ROOT	out
止	VV	i	8	-NONE-	in
出	VV	b	8	ROOT	out
现	VV	i	10	-NONE-	in
无	JJ	b	15	ROOT	out
序	JJ	i	12	-NONE-	in
现	NN	b	15	-NONE-	in
象	NN	i	10	ROOT	out
，	PU	b	47	ROOT	out
新	NN	b	18	-NONE-	in
区	NN	i	21	ROOT	out
管	NN	b	20	-NONE-	in
委	NN	i	21	-NONE-	in
会	NN	i	47	ROOT	out
根	P	b	23	-NONE-	in
据	P	i	47	ROOT	out
国	NN	b	25	-NONE-	in
家	NN	i	29	ROOT	out
和	CC	b	29	ROOT	out
上	NR	b	28	-NONE-	in
海	NR	i	29	-NONE-	in
市	NR	i	30	ROOT	out
的	DEG	b	34	ROOT	out
有	JJ	b	34	ROOT	out
关	JJ	i	31	-NONE-	in
规	NN	b	34	-NONE-	in
定	NN	i	23	ROOT	out
，	PU	b	47	ROOT	out
结	VV	b	47	ROOT	out
合	VV	i	36	-NONE-	in
浦	NR	b	39	-NONE-	in
东	NR	i	40	ROOT	out
开	NN	b	43	ROOT	out
发	NN	i	40	-NONE-	in
实	NN	b	43	-NONE-	in
际	NN	i	36	ROOT	out
，	PU	b	47	ROOT	out
及	AD	b	47	ROOT	out
时	AD	i	45	-NONE-	in
出	VV	b	131	ROOT	out
台	VV	i	47	-NONE-	in
了	AS	b	47	ROOT	out
一	CD	b	52	ROOT	out
系	M	b	52	-NONE-	in
列	M	i	61	ROOT	out
规	VV	b	54	-NONE-	in
范	VV	i	59	ROOT	out
建	NN	b	58	ROOT	out
设	NN	i	55	-NONE-	in
市	NN	b	58	-NONE-	in
场	NN	i	54	ROOT	out
的	DEC	b	61	ROOT	out
文	NN	b	61	-NONE-	in
件	NN	i	47	ROOT	out
，	PU	b	131	ROOT	out
其	NN	b	64	-NONE-	in
中	NN	i	65	ROOT	out
包	VV	b	131	ROOT	out
括	VV	i	65	-NONE-	in
工	NN	b	68	-NONE-	in
程	NN	i	77	ROOT	out
施	NN	b	77	ROOT	out
工	NN	i	69	-NONE-	in
招	NN	b	73	-NONE-	in
投	NN	i	71	-NONE-	in
标	NN	i	77	ROOT	out
管	NN	b	77	ROOT	out
理	NN	i	74	-NONE-	in
办	NN	b	77	-NONE-	in
法	NN	i	126	ROOT	out
、	PU	b	126	ROOT	out
拆	NN	b	82	ROOT	out
迁	NN	i	79	-NONE-	in
工	NN	b	82	-NONE-	in
作	NN	i	86	ROOT	out
若	CD	b	84	-NONE-	in
干	CD	i	86	ROOT	out
规	NN	b	86	-NONE-	in
定	NN	i	126	ROOT	out
、	PU	b	126	ROOT	out
整	VV	b	97	ROOT	out
治	VV	i	88	-NONE-	in
违	JJ	b	92	ROOT	out
章	JJ	i	90	-NONE-	in
建	NN	b	88	ROOT	out
筑	NN	i	92	-NONE-	in
实	NN	b	95	-NONE-	in
施	NN	i	97	ROOT	out
办	NN	b	97	-NONE-	in
法	NN	i	126	ROOT	out
、	PU	b	126	ROOT	out
通	NN	b	106	ROOT	out
信	NN	i	99	-NONE-	in
设	NN	b	106	ROOT	out
施	NN	i	101	-NONE-	in
及	CC	b	106	ROOT	out
管	NN	b	105	-NONE-	in
线	NN	i	106	ROOT	out
配	NN	b	111	ROOT	out
套	NN	i	106	-NONE-	in
建	NN	b	111	ROOT	out
设	NN	i	108	-NONE-	in
意	NN	b	111	-NONE-	in
见	NN	i	126	ROOT	out
、	PU	b	126	ROOT	out
建	NN	b	121	ROOT	out
设	NN	i	113	-NONE-	in
工	NN	b	116	-NONE-	in
地	NN	i	121	ROOT	out
施	NN	b	121	ROOT	out
工	NN	i	117	-NONE-	in
环	NN	b	120	-NONE-	in
境	NN	i	121	ROOT	out
管	NN	b	126	ROOT	out
理	NN	i	121	-NONE-	in
暂	JJ	b	124	-NONE-	in
行	JJ	i	126	ROOT	out
办	NN	b	126	-NONE-	in
法	NN	i	65	ROOT	out
等	ETC	b	126	ROOT	out
，	PU	b	131	ROOT	out
基	AD	b	130	-NONE-	in
本	AD	i	131	ROOT	out
做	VV	b	-1	ROOT	out
到	VV	i	131	-NONE-	in
了	AS	b	131	ROOT	out
每	DT	b	135	ROOT	out
个	M	b	137	ROOT	out
环	NN	b	137	-NONE-	in
节	NN	i	139	ROOT	out
都	AD	b	139	ROOT	out
有	VE	b	131	ROOT	out
明	VA	b	141	-NONE-	in
确	VA	i	146	ROOT	out
而	CC	b	141	ROOT	out
又	AD	b	145	ROOT	out
具	VA	b	145	-NONE-	in
体	VA	i	141	ROOT	out
的	DEC	b	148	ROOT	out
规	NN	b	148	-NONE-	in
定	NN	i	139	ROOT	out
。	PU	b	131	ROOT	out

建	NN	b	3	ROOT	out
筑	NN	i	0	-NONE-	in
公	NN	b	3	-NONE-	in
司	NN	i	4	ROOT	out
进	VV	b	24	ROOT	out
区	NN	b	4	ROOT	out
，	PU	b	24	ROOT	out
有	JJ	b	10	ROOT	out
关	JJ	i	7	-NONE-	in
部	NN	b	10	-NONE-	in
门	NN	i	12	ROOT	out
先	AD	b	12	ROOT	out
送	VV	b	24	ROOT	out
上	VV	i	12	-NONE-	in
这	DT	b	15	-NONE-	in
些	DT	i	20	ROOT	out
法	NN	b	17	-NONE-	in
规	NN	i	18	-NONE-	in
性	NN	i	20	ROOT	out
文	NN	b	20	-NONE-	in
件	NN	i	12	ROOT	out
，	PU	b	24	ROOT	out
然	AD	b	23	-NONE-	in
后	AD	i	24	ROOT	out
有	VE	b	-1	ROOT	out
专	JJ	b	26	-NONE-	in
门	JJ	i	28	ROOT	out
队	NN	b	28	-NONE-	in
伍	NN	i	29	ROOT	out
进	VV	b	24	ROOT	out
行	VV	i	29	-NONE-	in
监	NN	b	33	ROOT	out
督	NN	i	31	-NONE-	in
检	NN	b	29	ROOT	out
查	NN	i	33	-NONE-	in
。	PU	b	24	ROOT	out

尽	CS	b	1	-NONE-	in
管	CS	i	61	ROOT	out
浦	NR	b	3	-NONE-	in
东	NR	i	5	ROOT	out
新	NN	b	5	-NONE-	in
区	NN	i	6	ROOT	out
制	VV	b	8	ROOT	out
定	VV	i	6	-NONE-	in
的	DEC	b	13	ROOT	out
法	NN	b	10	-NONE-	in
规	NN	i	11	-NONE-	in
性	NN	i	13	ROOT	out
文	NN	b	13	-NONE-	in
件	NN	i	26	ROOT	out
有	PN	b	18	ROOT	out
些	PN	i	14	-NONE-	in
比	AD	b	18	ROOT	out
较	AD	i	16	-NONE-	in
“	PU	b	26	ROOT	out
粗	VA	b	18	ROOT	out
”	PU	b	18	ROOT	out
，	PU	b	26	ROOT	out
有	PN	b	26	ROOT	out
些	PN	i	22	-NONE-	in
还	AD	b	26	ROOT	out
只	AD	b	26	ROOT	out
是	VC	b	1	ROOT	out
暂	JJ	b	28	-NONE-	in
行	JJ	i	30	ROOT	out
规	NN	b	30	-NONE-	in
定	NN	i	26	ROOT	out
，	PU	b	26	ROOT	out
有	VV	b	26	ROOT	out
待	VV	i	32	-NONE-	in
在	P	b	40	ROOT	out
实	NN	b	36	-NONE-	in
践	NN	i	37	ROOT	out
中	LC	b	34	ROOT	out
逐	AD	b	39	-NONE-	in
步	AD	i	40	ROOT	out
完	VV	b	32	ROOT	out
善	VV	i	40	-NONE-	in
，	PU	b	61	ROOT	out
但	AD	b	61	ROOT	out
这	DT	b	45	ROOT	out
种	M	b	59	ROOT	out
法	NN	b	47	-NONE-	in
制	NN	i	49	ROOT	out
紧	VV	b	49	-NONE-	in
跟	VV	i	57	ROOT	out
经	NN	b	51	-NONE-	in
济	NN	i	54	ROOT	out
和	CC	b	54	ROOT	out
社	NN	b	54	-NONE-	in
会	NN	i	55	ROOT	out
活	NN	b	49	ROOT	out
动	NN	i	55	-NONE-	in
的	DEC	b	59	ROOT	out
做	NN	b	59	-NONE-	in
法	NN	i	61	ROOT	out
，	PU	b	61	ROOT	out
受	VV	b	76	ROOT	out
到	VV	i	61	-NONE-	in
了	AS	b	61	ROOT	out
国	NN	b	66	-NONE-	in
内	NN	i	66	-NONE-	in
外	NN	i	69	ROOT	out
投	NN	b	69	-NONE-	in
资	NN	i	67	-NONE-	in
者	NN	i	70	ROOT	out
的	DEG	b	72	ROOT	out
好	JJ	b	72	ROOT	out
评	NN	b	61	ROOT	out
，	PU	b	76	ROOT	out
他	PN	b	76	ROOT	out
们	PN	i	74	-NONE-	in
认	VV	b	-1	ROOT	out
为	VV	i	76	-NONE-	in
，	PU	b	76	ROOT	out
到	VV	b	98	ROOT	out
浦	NR	b	81	-NONE-	in
东	NR	i	83	ROOT	out
新	NN	b	83	-NONE-	in
区	NN	i	79	ROOT	out
投	VV	b	79	ROOT	out
资	VV	i	84	-NONE-	in
办	NN	b	88	ROOT	out
事	NN	i	86	-NONE-	in
有	VE	b	98	ROOT	out
章	NN	b	90	-NONE-	in
法	NN	i	88	ROOT	out
，	PU	b	88	ROOT	out
讲	VV	b	88	ROOT	out
规	NN	b	94	-NONE-	in
矩	NN	i	92	ROOT	out
，	PU	b	98	ROOT	out
利	NN	b	97	-NONE-	in
益	NN	i	98	ROOT	out
能	VV	b	76	ROOT	out
得	VV	b	98	ROOT	out
到	VV	i	99	-NONE-	in
保	NN	b	99	ROOT	out
障	NN	i	101	-NONE-	in
。	PU	b	76	ROOT	out

（	PU	b	1	ROOT	out
完	VV	b	-1	ROOT	out
）	PU	b	1	ROOT	out

外	NN	b	1	-NONE-	in
商	NN	i	5	ROOT	out
投	NN	b	5	ROOT	out
资	NN	i	2	-NONE-	in
企	NN	b	5	-NONE-	in
业	NN	i	6	ROOT	out
成	VV	b	-1	ROOT	out
为	VV	i	6	-NONE-	in
中	NR	b	9	-NONE-	in
国	NR	i	11	ROOT	out
外	NN	b	11	-NONE-	in
贸	NN	i	16	ROOT	out
重	JJ	b	16	ROOT	out
要	JJ	i	12	-NONE-	in
增	NN	b	16	-NONE-	in
长	NN	i	14	-NONE-	in
点	NN	i	6	ROOT	out

新	NN	b	1	-NONE-	in
华	NN	i	2	-NONE-	in
社	NN	i	15	ROOT	out
北	NR	b	4	-NONE-	in
京	NR	i	15	ROOT	out
二	NT	b	6	-NONE-	in
月	NT	i	15	ROOT	out
十	NT	b	8	-NONE-	in
一	NT	i	9	-NONE-	in
日	NT	i	15	ROOT	out
电	NN	b	15	ROOT	out
（	PU	b	15	ROOT	out
记	NN	b	13	-NONE-	in
者	NN	i	15	ROOT	out
唐	NR	b	15	-NONE-	in
虹	NR	i	-1	ROOT	out
）	PU	b	15	ROOT	out

海	NN	b	1	-NONE-	in
关	NN	i	3	ROOT	out
统	NN	b	3	-NONE-	in
计	NN	i	4	ROOT	out
表	VV	b	-1	ROOT	out
明	VV	i	4	-NONE-	in
，	PU	b	4	ROOT	out
“	PU	b	9	ROOT	out
八	NT	b	9	-NONE-	in
五	NT	i	12	ROOT	out
”	PU	b	9	ROOT	out
期	NN	b	12	-NONE-	in
间	NN	i	66	ROOT	out
（	PU	b	12	ROOT	out
一	NT	b	15	-NONE-	in
九	NT	i	16	-NONE-	in
九	NT	i	18	-NONE-	in
０	NT	i	16	-NONE-	in
年	NT	i	24	ROOT	out
—	PU	b	24	ROOT	out
一	NT	b	21	-NONE-	in
九	NT	i	22	-NONE-	in
九	NT	i	23	-NONE-	in
五	NT	i	24	-NONE-	in
年	NT	i	13	ROOT	out
）	PU	b	13	ROOT	out
，	PU	b	66	ROOT	out
中	NR	b	28	-NONE-	in
国	NR	i	34	ROOT	out
外	NN	b	30	-NONE-	in
商	NN	i	34	ROOT	out
投	NN	b	34	ROOT	out
资	NN	i	31	-NONE-	in
企	NN	b	34	-NONE-	in
业	NN	i	35	ROOT	out
的	DEG	b	36	ROOT	out
进	NN	b	39	ROOT	out
出	NN	i	36	-NONE-	in
口	NN	i	36	-NONE-	in
呈	VV	b	66	ROOT	out
直	AD	b	41	-NONE-	in
线	AD	i	43	ROOT	out
上	VV	b	43	-NONE-	in
升	VV	i	44	ROOT	out
之	DEC	b	45	ROOT	out
势	NN	b	39	ROOT	out
，	PU	b	66	ROOT	out
出	NN	b	51	ROOT	out
口	NN	i	47	-NONE-	in
年	AD	b	50	-NONE-	in
均	AD	i	51	ROOT	out
增	VV	b	66	ROOT	out
长	VV	i	51	-NONE-	in
百	CD	b	54	-NONE-	in
分	CD	i	55	-NONE-	in
之	CD	i	56	-NONE-	in
四	CD	i	57	-NONE-	in
十	CD	i	58	-NONE-	in
三	CD	i	59	-NONE-	in
点	CD	i	60	-NONE-	in
二	CD	i	51	ROOT	out
，	PU	b	66	ROOT	out
进	NN	b	66	ROOT	out
口	NN	i	62	-NONE-	in
年	AD	b	65	-NONE-	in
均	AD	i	66	ROOT	out
增	VV	b	4	ROOT	out
长	VV	i	66	-NONE-	in
百	CD	b	69	-NONE-	in
分	CD	i	70	-NONE-	in
之	CD	i	71	-NONE-	in
三	CD	i	72	-NONE-	in
十	CD	i	73	-NONE-	in
八	CD	i	74	-NONE-	in
点	CD	i	75	-NONE-	in
六	CD	i	66	ROOT	out
。	PU	b	4	ROOT	out

去	NT	b	1	-NONE-	in
年	NT	i	3	ROOT	out
实	VV	b	3	-NONE-	in
现	VV	i	8	ROOT	out
进	NN	b	8	ROOT	out
出	NN	i	4	-NONE-	in
口	NN	i	4	-NONE-	in
总	NN	b	8	-NONE-	in
值	NN	i	9	ROOT	out
达	VV	b	43	ROOT	out
一	CD	b	11	-NONE-	in
千	CD	i	12	-NONE-	in
零	CD	i	13	-NONE-	in
九	CD	i	14	-NONE-	in
十	CD	i	15	-NONE-	in
八	CD	i	16	-NONE-	in
点	CD	i	17	-NONE-	in
二	CD	i	18	-NONE-	in
亿	CD	i	20	ROOT	out
美	M	b	20	-NONE-	in
元	M	i	9	ROOT	out
，	PU	b	43	ROOT	out
占	VV	b	30	ROOT	out
全	DT	b	24	ROOT	out
国	NN	b	29	ROOT	out
进	NN	b	29	ROOT	out
出	NN	i	25	-NONE-	in
口	NN	i	25	-NONE-	in
总	NN	b	29	-NONE-	in
值	NN	i	22	ROOT	out
的	DEC	b	31	ROOT	out
比	NN	b	43	ROOT	out
重	NN	i	31	-NONE-	in
由	P	b	43	ROOT	out
上	DT	b	35	ROOT	out
年	M	b	36	ROOT	out
的	DEG	b	42	ROOT	out
百	CD	b	38	-NONE-	in
分	CD	i	39	-NONE-	in
之	CD	i	40	-NONE-	in
三	CD	i	41	-NONE-	in
十	CD	i	42	-NONE-	in
七	CD	i	33	ROOT	out
提	VV	b	-1	ROOT	out
高	VV	i	43	-NONE-	in
到	VV	b	43	ROOT	out
百	CD	b	47	-NONE-	in
分	CD	i	48	-NONE-	in
之	CD	i	49	-NONE-	in
三	CD	i	50	-NONE-	in
十	CD	i	51	-NONE-	in
九	CD	i	43	ROOT	out
。	PU	b	43	ROOT	out

外	NN	b	1	-NONE-	in
商	NN	i	5	ROOT	out
投	NN	b	5	ROOT	out
资	NN	i	2	-NONE-	in
企	NN	b	5	-NONE-	in
业	NN	i	18	ROOT	out
在	P	b	18	ROOT	out
改	VV	b	17	ROOT	out
善	VV	i	7	-NONE-	in
中	NR	b	10	-NONE-	in
国	NR	i	16	ROOT	out
出	NN	b	16	ROOT	out
口	NN	i	11	-NONE-	in
商	NN	b	14	-NONE-	in
品	NN	i	16	ROOT	out
结	NN	b	16	-NONE-	in
构	NN	i	7	ROOT	out
中	LC	b	6	ROOT	out
发	VV	b	-1	ROOT	out
挥	VV	i	18	-NONE-	in
了	AS	b	18	ROOT	out
显	JJ	b	23	ROOT	out
著	JJ	i	21	-NONE-	in
作	NN	b	18	ROOT	out
用	NN	i	23	-NONE-	in
。	PU	b	18	ROOT	out

去	NT	b	1	-NONE-	in
年	NT	i	19	ROOT	out
外	NN	b	3	-NONE-	in
商	NN	i	11	ROOT	out
投	NN	b	11	ROOT	out
资	NN	i	4	-NONE-	in
企	NN	b	7	-NONE-	in
业	NN	i	11	ROOT	out
出	NN	b	11	ROOT	out
口	NN	i	8	-NONE-	in
商	NN	b	11	-NONE-	in
品	NN	i	12	ROOT	out
中	LC	b	19	ROOT	out
，	PU	b	19	ROOT	out
工	NN	b	15	-NONE-	in
业	NN	i	18	ROOT	out
制	NN	b	18	-NONE-	in
成	NN	i	16	-NONE-	in
品	NN	i	19	ROOT	out
占	VV	b	-1	ROOT	out
九	CD	b	21	-NONE-	in
成	CD	i	23	ROOT	out
以	LC	b	23	-NONE-	in
上	LC	i	19	ROOT	out
，	PU	b	19	ROOT	out
达	VV	b	19	ROOT	out
四	CD	b	27	-NONE-	in
百	CD	i	28	-NONE-	in
三	CD	i	29	-NONE-	in
十	CD	i	30	-NONE-	in
八	CD	i	31	-NONE-	in
点	CD	i	32	-NONE-	in
八	CD	i	33	-NONE-	in
亿	CD	i	35	ROOT	out
美	M	b	35	-NONE-	in
元	M	i	25	ROOT	out
，	PU	b	19	ROOT	out
比	P	b	40	ROOT	out
上	DT	b	39	ROOT	out
年	M	b	37	ROOT	out
增	VV	b	19	ROOT	out
长	VV	i	40	-NONE-	in
了	AS	b	40	ROOT	out
百	CD	b	44	-NONE-	in
分	CD	i	45	-NONE-	in
之	CD	i	46	-NONE-	in
三	CD	i	47	-NONE-	in
十	CD	i	48	-NONE-	in
六	CD	i	49	-NONE-	in
点	CD	i	50	-NONE-	in
七	CD	i	40	ROOT	out
，	PU	b	19	ROOT	out
明	AD	b	53	-NONE-	in
显	AD	i	54	ROOT	out
高	VV	b	19	ROOT	out
于	VV	i	54	-NONE-	in
全	DT	b	57	ROOT	out
国	NN	b	61	ROOT	out
平	JJ	b	61	ROOT	out
均	JJ	i	58	-NONE-	in
水	NN	b	61	-NONE-	in
平	NN	i	54	ROOT	out
。	PU	b	19	ROOT	out

外	NN	b	1	-NONE-	in
商	NN	i	5	ROOT	out
投	NN	b	5	ROOT	out
资	NN	i	2	-NONE-	in
企	NN	b	5	-NONE-	in
业	NN	i	6	ROOT	out
的	DEG	b	10	ROOT	out
出	NN	b	10	ROOT	out
口	NN	i	7	-NONE-	in
商	NN	b	10	-NONE-	in
品	NN	i	17	ROOT	out
仍	AD	b	17	ROOT	out
以	P	b	17	ROOT	out
轻	NN	b	14	-NONE-	in
纺	NN	i	16	ROOT	out
产	NN	b	16	-NONE-	in
品	NN	i	12	ROOT	out
为	VV	b	37	ROOT	out
主	VV	i	17	-NONE-	in
，	PU	b	37	ROOT	out
其	NN	b	21	-NONE-	in
中	NN	i	31	ROOT	out
，	PU	b	31	ROOT	out
出	NN	b	25	-NONE-	in
口	NN	i	23	-NONE-	in
额	NN	i	27	ROOT	out
最	AD	b	27	ROOT	out
大	VA	b	28	ROOT	out
的	DEC	b	30	ROOT	out
商	NN	b	30	-NONE-	in
品	NN	i	31	ROOT	out
是	VC	b	37	ROOT	out
服	NN	b	33	-NONE-	in
装	NN	i	31	ROOT	out
，	PU	b	37	ROOT	out
去	NT	b	36	-NONE-	in
年	NT	i	37	ROOT	out
为	VC	b	-1	ROOT	out
七	CD	b	39	-NONE-	in
十	CD	i	40	-NONE-	in
六	CD	i	41	-NONE-	in
点	CD	i	42	-NONE-	in
八	CD	i	43	-NONE-	in
亿	CD	i	45	ROOT	out
美	M	b	45	-NONE-	in
元	M	i	37	ROOT	out
。	PU	b	37	ROOT	out


